services: 
  server-1:
    container_name: server-1
    build: ./server-1
    ports:
      - 8001:8001
    networks:
      - minor-project
    depends_on:
      - mongo
    restart: always
    
  server-2:
    container_name: server-2
    build: ./server-2
    ports:
      - 8002:8002
    networks:
      - minor-project
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 80:27017
    networks:
      - minor-project
    restart: always
    volumes:
      - ./db/:/data/db/


networks:
  minor-project:
    name: minor-project
    ipam:
      driver: default
      config:
        - subnet: "182.182.0.0/24"